import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { applyToJob, favoriteJob, unfavoriteJob } from "../api/jobs";
import { getRegions } from "../api/regions";
import { hasSession } from "../auth/session";
import { Status } from "../components/UI";
import { asList, useApi } from "../hooks/useApi";

export default function JobDetailPage() {
  const { id } = useParams(); const { data: job, loading, error } = useApi(`/api/v1/jobs/${id}`);
  const [favorite, setFavorite] = useState(false); const [applyOpen, setApplyOpen] = useState(false); const [message, setMessage] = useState(""); const [applicationMessage, setApplicationMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [regions, setRegions] = useState([]);
  const valid = job && (job.id || job.title || job.employerName);
  useEffect(() => { if (job) setFavorite(Boolean(job.favorite)); }, [job]);
  useEffect(() => { getRegions().then((result) => setRegions(asList(result, "regions"))).catch(() => {}); }, []);
  async function toggleFavorite() { if (!hasSession()) return setMessage("로그인 후 찜할 수 있어요."); setBusy(true); try { if (favorite) await unfavoriteJob(id); else await favoriteJob(id); setFavorite(!favorite); setMessage(favorite ? "찜을 취소했습니다." : "찜한 일자리에 추가했습니다."); } catch (e) { setMessage(e.message); } finally { setBusy(false); } }
  async function apply() { if (!hasSession()) { setMessage("로그인 후 지원할 수 있어요."); setApplyOpen(false); return; } if (!applicationMessage.trim()) return setMessage("지원 메시지를 입력해 주세요."); setBusy(true); try { await applyToJob(id, applicationMessage.trim()); setMessage("지원이 완료되었습니다."); setApplicationMessage(""); setApplyOpen(false); } catch (e) { setMessage(e.message); } finally { setBusy(false); } }
  return <main className="job-detail-main"><section className="job-detail-intro"><div><p className="eyebrow dark">일자리 찾기</p><h1>{valid ? job.title : "공고 상세 정보"}</h1></div><p>업무·위치·근무 조건을 확인하고 지원 여부를 결정해 보세요.</p></section><Status loading={loading} error={error} empty={!valid}>{valid && <div className="job-detail-workspace">
    <aside className="job-criteria-card"><div className="job-detail-card-head"><h2>일자리 검색</h2><span>DB 공고</span></div><p className="job-detail-search-copy">원하는 조건을 선택하면 등록된 일자리 목록으로 이동해요.</p><form className="job-detail-search-form"><label>지역<select name="region" defaultValue={job.regionName || ""}><option value="">전체 지역</option>{regions.map((region)=><option value={region.name} key={region.regionId || region.id || region.name}>{region.name}</option>)}</select></label><fieldset><legend>여행 기간</legend><div><label>출발일<input name="tripStart" type="date" /></label><label>도착일<input name="tripEnd" type="date" /></label></div><p>여행 일정으로 추천 결과를 좁혀 보여드려요.</p></fieldset><div className="job-detail-secondary-actions"><Link className="button button-primary job-detail-search-button" to={`/jobs${job.regionName ? `?region=${encodeURIComponent(job.regionName)}` : ""}`}>조건으로 검색하기</Link><Link className="button job-detail-back-button" to="/jobs">목록으로 돌아가기</Link></div></form><section className="job-apply-card"><div><p>지원 안내</p><h3>이 공고가 마음에 드나요?</h3><span>담당자에게 문의하고 근무 일정을 확인해 보세요.</span></div><div className="job-apply-actions"><button className="button button-primary" disabled={busy} onClick={() => setApplyOpen(true)}>공고 지원하기</button><button className="button job-favorite-button" disabled={busy} aria-pressed={favorite} onClick={toggleFavorite}>{favorite ? "♥" : "♡"}</button></div></section>{message && <div className="page-status is-visible">{message}</div>}</aside>
    <section className="job-detail-results"><p className="result-kind">공고 상세 정보</p><article className="job-insight-card"><img className="job-insight-photo" src="/assets/OZ3bs.jpeg" alt="지역 관광 일자리 현장" /><div><p className="eyebrow">추천 포인트</p><h2>지역 여행 동선과 이어지는 공고예요</h2><p>{job.description || `${job.regionName || "전라도"} 관광 생활권에서 경험할 수 있는 일자리입니다.`}</p><div className="job-insight-chips">{[job.workType,job.workHours,job.employmentPeriod].filter(Boolean).map((item)=><span key={item}>{item}</span>)}</div></div></article><article className="job-detail-hero-card"><p className="eyebrow">{job.regionName} · {job.category || "관광 일자리"}</p><h2>{job.title}</h2><p>{job.employerName}</p><div className="job-detail-metrics"><div><span>급여</span><strong>{job.salaryText || "조건 협의"}</strong></div><div><span>근무 시간</span><strong>{job.workHours || "협의"}</strong></div><div><span>평점</span><strong>★ {job.rating || "-"}</strong></div></div></article><section className="job-accordion-section"><h2>근무 일정</h2><details><summary>운영 조건 보기</summary><div className="job-accordion-body"><span>{job.employmentPeriod || "근무 기간 협의"}</span><span>{job.workHours || "근무 시간 협의"}</span><span>{job.workType || "근무 형태 협의"}</span></div></details></section><article className="job-location-card"><div><p className="eyebrow">위치</p><h2>{job.location || job.regionName}</h2><p>지원 전 담당자에게 상세 주소와 출근 방법을 확인해 주세요.</p></div><div className="job-mini-map"><b>근무 위치</b><span>N</span><small>{job.regionName}</small></div></article><article className="job-duties-card"><h2>무엇을 하게 되나요?</h2><div className="job-duty-row"><span>•</span><div><strong>관광객 안내</strong><p>방문객에게 주요 구역과 이동 동선을 안내합니다.</p></div></div><div className="job-duty-row"><span>•</span><div><strong>현장 운영 보조</strong><p>지역 콘텐츠와 프로그램 운영을 지원합니다.</p></div></div></article></section>
  </div>}</Status>{applyOpen && <div className="job-apply-modal"><button className="job-apply-backdrop" aria-label="닫기" onClick={() => setApplyOpen(false)} /><section className="job-apply-dialog"><p className="eyebrow">지원 안내</p><h2>이 공고에 지원할까요?</h2><p className="job-apply-description">지원 내역은 마이페이지에서 확인할 수 있어요.</p><label className="job-application-message">지원 메시지<textarea rows="5" value={applicationMessage} placeholder="관광객 응대 경험이 있어 지원합니다." onChange={(event) => setApplicationMessage(event.target.value)} /></label><button className="button button-primary" disabled={busy} onClick={apply}>지원하기</button><button className="button job-apply-close" onClick={() => setApplyOpen(false)}>닫기</button></section></div>}</main>;
}
