import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { apiRequest } from "../api/client";
import { hasSession } from "../auth/session";
import { Status } from "../components/UI";
import { useApi } from "../hooks/useApi";

export default function JobDetailPage() {
  const { id } = useParams(); const { data: job, loading, error } = useApi(`/api/jobs/${id}`);
  const [favorite, setFavorite] = useState(false); const [applyOpen, setApplyOpen] = useState(false); const [message, setMessage] = useState("");
  const valid = job && (job.id || job.title || job.companyName);
  useEffect(() => { if (hasSession()) apiRequest(`/api/jobs/${id}/favorite`).then((r) => setFavorite(Boolean(r.favorite))).catch(() => {}); }, [id]);
  async function toggleFavorite() { if (!hasSession()) return setMessage("로그인 후 찜할 수 있어요."); try { await apiRequest(`/api/jobs/${id}/favorite`, { method: favorite ? "DELETE" : "POST" }); setFavorite(!favorite); } catch (e) { setMessage(e.message); } }
  async function apply() { if (!hasSession()) { setMessage("로그인 후 지원할 수 있어요."); setApplyOpen(false); return; } try { await apiRequest(`/api/jobs/${id}/apply`, { method: "POST", body: "{}" }); setMessage("지원 내역에 저장했습니다."); setApplyOpen(false); } catch (e) { setMessage(e.message); } }
  return <main className="job-detail-main"><section className="job-detail-intro"><div><p className="eyebrow dark">일자리 찾기</p><h1>{valid ? job.title : "공고 상세 정보"}</h1></div><p>업무·위치·근무 조건을 확인하고 지원 여부를 결정해 보세요.</p></section><Status loading={loading} error={error} empty={!valid}>{valid && <div className="job-detail-workspace">
    <aside className="job-criteria-card"><div className="job-detail-card-head"><h2>일자리 검색</h2><span>DB 공고</span></div><p className="job-detail-search-copy">원하는 조건을 선택하면 등록된 일자리 목록으로 이동해요.</p><form className="job-detail-search-form"><label>지역<select name="region" defaultValue={job.region || ""}><option value="">전체 지역</option>{["전주","군산","남원","목포","광주","순천","여수","보성","완도"].map((r)=><option key={r}>{r}</option>)}</select></label><fieldset><legend>여행 기간</legend><div><label>출발일<input name="tripStart" type="date" /></label><label>도착일<input name="tripEnd" type="date" /></label></div><p>여행 일정으로 추천 결과를 좁혀 보여드려요.</p></fieldset><div className="job-detail-secondary-actions"><Link className="button button-primary job-detail-search-button" to={`/jobs${job.region ? `?region=${encodeURIComponent(job.region)}` : ""}`}>조건으로 검색하기</Link><Link className="button job-detail-back-button" to="/jobs">목록으로 돌아가기</Link></div></form><section className="job-apply-card"><div><p>지원 안내</p><h3>이 공고가 마음에 드나요?</h3><span>담당자에게 문의하고 근무 일정을 확인해 보세요.</span></div><div className="job-apply-actions"><button className="button button-primary" onClick={() => setApplyOpen(true)}>공고 지원하기</button><button className="button job-favorite-button" aria-pressed={favorite} onClick={toggleFavorite}>{favorite ? "♥" : "♡"}</button></div></section>{message && <div className="page-status is-visible">{message}</div>}</aside>
    <section className="job-detail-results"><p className="result-kind">공고 상세 정보</p><article className="job-insight-card"><img className="job-insight-photo" src="/assets/OZ3bs.jpeg" alt="지역 관광 일자리 현장" /><div><p className="eyebrow">추천 포인트</p><h2>지역 여행 동선과 이어지는 공고예요</h2><p>{job.description || `${job.region} 관광 생활권에서 경험할 수 있는 일자리입니다.`}</p><div className="job-insight-chips">{[job.workType,job.workTime,job.duration].filter(Boolean).map((item)=><span key={item}>{item}</span>)}</div></div></article><article className="job-detail-hero-card"><p className="eyebrow">{job.region} · {job.category || "관광 일자리"}</p><h2>{job.title}</h2><p>{job.companyName}</p><div className="job-detail-metrics"><div><span>급여</span><strong>{job.pay || "조건 협의"}</strong></div><div><span>근무 시간</span><strong>{job.workTime || "협의"}</strong></div><div><span>평점</span><strong>★ {job.rating || "-"}</strong></div></div></article><section className="job-accordion-section"><h2>근무 일정</h2><details><summary>운영 조건 보기</summary><div className="job-accordion-body"><span>{job.duration || "근무 기간 협의"}</span><span>{job.workTime || "근무 시간 협의"}</span><span>현장 안내 후 업무 시작</span></div></details></section><article className="job-location-card"><div><p className="eyebrow">위치</p><h2>{job.location || job.region}</h2><p>지원 전 담당자에게 상세 주소와 출근 방법을 확인해 주세요.</p></div><div className="job-mini-map"><b>근무 위치</b><span>N</span><small>{job.region}</small></div></article><article className="job-duties-card"><h2>무엇을 하게 되나요?</h2><div className="job-duty-row"><span>•</span><div><strong>관광객 안내</strong><p>방문객에게 주요 구역과 이동 동선을 안내합니다.</p></div></div><div className="job-duty-row"><span>•</span><div><strong>현장 운영 보조</strong><p>지역 콘텐츠와 프로그램 운영을 지원합니다.</p></div></div></article></section>
  </div>}</Status>{applyOpen && <div className="job-apply-modal"><button className="job-apply-backdrop" aria-label="닫기" onClick={() => setApplyOpen(false)} /><section className="job-apply-dialog"><p className="eyebrow">지원 안내</p><h2>이 공고에 지원할까요?</h2><p className="job-apply-description">지원 내역은 마이페이지에서 확인할 수 있어요.</p><button className="button button-primary" onClick={apply}>지원하기</button><button className="button job-apply-close" onClick={() => setApplyOpen(false)}>닫기</button></section></div>}</main>;
}
